filter:
    excluded_paths: [vendor/*, app/*, web/*]

tools:
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor]
    external_code_coverage:
      timeout: 600
    php_analyzer:
      config:
        metrics_coupling:
          enabled: true
          stable_code:
            namespace_prefixes: []
            classes: []
        metrics_lack_of_cohesion_methods:
          enabled: true
