filter:
    excluded_paths: [vendor/*, tests/*, src/Conphig/Builders/*]

tools:
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor, tests]
    external_code_coverage: true
    php_analyzer:
      config:
        metrics_coupling:
          enabled: true
          stable_code:
            namespace_prefixes: []
            classes: []
        metrics_lack_of_cohesion_methods:
          enabled: true
