language: php
php:
  - 5.5

before_script:
  - composer self-update -vvv
  - composer install --dev --no-interaction -vvv

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml
  
after_script:
  - vendor/bin/coveralls -v
